init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
configuration:
  - CodeAnalysis
  - Release
matrix:
  fast_finish: true
before_build:
  - cmd: .\build.cmd EnableSkipStrongNames
build_script:
  - cmd: .\build.cmd UnitTest /P:Configuration=%Configuration%
clone_depth: 1
test: off
deploy: off
os: Visual Studio 2017
